# Generated by Django 5.2.17 on 2026-09-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, help_text="Buyer's stated budget in the marketplace's base currency.", max_digits=10)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(help_text='Full description of what the buyer wants created.')),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='List of reference image URLs (Cloudflare R2 objects).')),
                ('deadline', models.DateField(blank=True, help_text="Buyer's requested completion date.", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, limit_choices_to={'role': 'artist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_requests_received', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Request',
                'verbose_name_plural': 'Commission Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note attached to this status change (e.g. quote amount).')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who triggered this status change (artist, buyer, or admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='commissions.commissionrequest')),
            ],
            options={
                'verbose_name': 'Commission Status Log',
                'verbose_name_plural': 'Commission Status Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
