# Generated by Django 5.2.17 on 2026-09-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('medium', models.CharField(help_text="E.g. 'Oil on canvas', 'Watercolour', 'Charcoal'", max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('drawing', 'Drawing'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('printmaking', 'Printmaking'), ('digital', 'Digital'), ('textile', 'Textile'), ('other', 'Other')], default='other', max_length=50)),
                ('dimensions', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('process_note', models.TextField(blank=True, default='', help_text="Artist's description of how the piece was made (authenticity mechanism).")),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('extra_attributes', models.JSONField(blank=True, default=dict, help_text='Category-specific extra metadata as key/value pairs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1024)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as True for the main display image of the artwork.')),
                ('upload_order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order when multiple images exist.')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
            options={
                'verbose_name': 'Artwork Image',
                'verbose_name_plural': 'Artwork Images',
                'ordering': ['-is_primary', 'upload_order'],
            },
        ),
    ]
