/**
 * Mock Artwork Dataset for Galleria Art Marketplace
 * 
 * NOTE FOR BACKEND INTEGRATION:
 * This mock data represents the payload structure expected from the Django REST Framework API.
 * Target API endpoint when connecting to backend:
 *   - Base URL: http://localhost:8000/api/
 *   - Artworks List: http://localhost:8000/api/artworks/
 *   - Artwork Detail: http://localhost:8000/api/artworks/:id/ or http://localhost:8000/api/artworks/:slug/
 *   - Filter endpoints: http://localhost:8000/api/artworks/?category=Paintings&medium=Oil+on+Canvas&min_price=1000&max_price=10000
 */

import { Artwork } from "./types";

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: "art-101",
    title: "Ethereal Horizon in Vermilion",
    slug: "ethereal-horizon-in-vermilion",
    artist: {
      id: "artist-1",
      name: "Helena Vance",
      location: "Paris, France",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      bio: "Helena Vance explores atmospheric abstraction using raw mineral pigments and gold leaf strictly layered on Belgian linen.",
    },
    price: 4800,
    category: "Paintings",
    medium: "Oil on Canvas",
    dimensions: "40 x 50 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=85",
    additionalImages: [
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=85",
    ],
    description: "A commanding study in light and horizon line, 'Ethereal Horizon in Vermilion' blends deep scarlet tones with luminous mineral whites to invoke dawn over coastal salt flats.",
    isAvailable: true,
    isFeatured: true,
    edition: "Original 1 of 1",
  },
  {
    id: "art-102",
    title: "Symphony of Form & Void No. 4",
    slug: "symphony-of-form-void-no-4",
    artist: {
      id: "artist-2",
      name: "Marcus Thorne",
      location: "Kyoto, Japan",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      bio: "Sculptor and architect focusing on minimalist geometric balance using patinated bronze and Nero Marquina marble.",
    },
    price: 9200,
    category: "Sculpture",
    medium: "Bronze Sculpture",
    dimensions: "18 x 12 x 28 in",
    year: 2023,
    imageUrl: "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&w=1200&q=85",
    additionalImages: [
      "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=1200&q=85",
    ],
    description: "Cast in hand-patinated bronze, this architectural sculpture captures movement halted mid-gesture, casting dramatic geometric shadows under gallery spotlighting.",
    isAvailable: true,
    isFeatured: true,
    edition: "Edition 2 of 5",
  },
  {
    id: "art-103",
    title: "Chiaroscuro in Mist",
    slug: "chiaroscuro-in-mist",
    artist: {
      id: "artist-3",
      name: "Camille Dubois",
      location: "Zurich, Switzerland",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      bio: "Fine art photographer capturing high-contrast alpine stillness and brutalist architectural interplay.",
    },
    price: 2600,
    category: "Photography",
    medium: "Archival Inkjet Print",
    dimensions: "30 x 40 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=85",
    additionalImages: [
      "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=85",
    ],
    description: "Captured during early winter dawn in the Swiss Alps, printed on museum-grade Hahnemühle Photo Rag Baryta with archival pigment inks.",
    isAvailable: true,
    isFeatured: false,
    edition: "Limited Edition of 10",
  },
  {
    id: "art-104",
    title: "Fractal Resonance",
    slug: "fractal-resonance",
    artist: {
      id: "artist-4",
      name: "Aria Sterling",
      location: "Berlin, Germany",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80",
      bio: "Generative artist and algorithmic painter exploring organic mathematical patterns.",
    },
    price: 3400,
    category: "Digital Art",
    medium: "Digital Composition",
    dimensions: "36 x 36 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=85",
    description: "Generative fluid dynamic artwork rendered at 16K resolution and presented on ultra-clear acrylic print backing with aluminum cleat mounting.",
    isAvailable: true,
    isFeatured: true,
    edition: "Original 1 of 1",
  },
  {
    id: "art-105",
    title: "Monolith & Crimson Field",
    slug: "monolith-crimson-field",
    artist: {
      id: "artist-1",
      name: "Helena Vance",
      location: "Paris, France",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
      bio: "Helena Vance explores atmospheric abstraction using raw mineral pigments and gold leaf strictly layered on Belgian linen.",
    },
    price: 6500,
    category: "Paintings",
    medium: "Oil on Canvas",
    dimensions: "48 x 60 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=85",
    description: "An expansive color field piece with impasto textures, anchoring deep cadmium reds against matte obsidian central geometry.",
    isAvailable: true,
    isFeatured: false,
    edition: "Original 1 of 1",
  },
  {
    id: "art-106",
    title: "Silent Metamorphosis",
    slug: "silent-metamorphosis",
    artist: {
      id: "artist-5",
      name: "Dimitri Rossi",
      location: "Milan, Italy",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
      bio: "Master printmaker working with woodcut, copperplate etching, and hand-embossed cotton rag paper.",
    },
    price: 1850,
    category: "Printmaking",
    medium: "Fine Art Print",
    dimensions: "24 x 32 in",
    year: 2023,
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=85",
    description: "Hand-pulled copper etching printed on 300gsm Somerset Velvet paper, numbered and signed in graphite by the artist.",
    isAvailable: true,
    isFeatured: false,
    edition: "Edition 8 of 30",
  },
  {
    id: "art-107",
    title: "Solitude at 4,000 Meters",
    slug: "solitude-at-4000-meters",
    artist: {
      id: "artist-3",
      name: "Camille Dubois",
      location: "Zurich, Switzerland",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80",
      bio: "Fine art photographer capturing high-contrast alpine stillness and brutalist architectural interplay.",
    },
    price: 3100,
    category: "Photography",
    medium: "Archival Inkjet Print",
    dimensions: "40 x 60 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=85",
    description: "A stark minimalist black-and-white landscape depicting cloud inversion engulfing mountain ridges in the Bernese Oberland.",
    isAvailable: true,
    isFeatured: false,
    edition: "Edition 3 of 15",
  },
  {
    id: "art-108",
    title: "Organic Architecture in Cadmium",
    slug: "organic-architecture-in-cadmium",
    artist: {
      id: "artist-2",
      name: "Marcus Thorne",
      location: "Kyoto, Japan",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
      bio: "Sculptor and architect focusing on minimalist geometric balance using patinated bronze and Nero Marquina marble.",
    },
    price: 11500,
    category: "Sculpture",
    medium: "Bronze Sculpture",
    dimensions: "24 x 20 x 42 in",
    year: 2024,
    imageUrl: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=1200&q=85",
    description: "Large format indoor/outdoor bronze monolith with red ceramic enamel inlay along its central fissure.",
    isAvailable: true,
    isFeatured: true,
    edition: "Original 1 of 1",
  },
];
